name: MobBlocker
version: ${project.version}
main: me.bigtallahasee.mobblocker.MobBlocker
authors: [ Bigtallahasee ]
description: This plugin will allow you to easily blacklist any mob that you please!
commands:
  mb:
    description: This is the command to do anything you need with this plugin!
